spring:
  jpa:
    hibernate:
      ddl-auto: create

    database: mysql
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/solodb?serverTimezone=UTC&characterEncoding=UTF-8
    username: test01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver